kind: pipeline
name: default

trigger:
  branch:
    - main

steps:
# - name: build_and_push_image
#   image: plugins/docker
#   settings:
#     repo: lholter/pcjazzerne
#     registry: docker.io
#     username:
#       from_secret: DOCKER_USERNAME
#     password:
#       from_secret: DOCKER_TOKEN
#     tags: latest
#     dockerfile: Dockerfile

- name: update_service
  image: docker/compose:1.29.2
  volumes:
    - name: docker-socket
      path: /var/run/docker.sock
  commands:
    - up -d
    - docker-compose pull
    - docker-compose up -d

# steps:
# - name: test
#   image: compose:1.23.2
#   volumes:
#   - name: docker_sock
#     path: /var/run/docker.sock
#   commands:
#   - up -f /drone/src/docker-compose.yaml
volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
