kind: pipeline
name: default

trigger:
  branch:
    - main

steps:
# - name: build_and_push_image
#   image: plugins/docker
#   settings:
#     repo: lholter/pcjazzerne
#     registry: docker.io
#     username:
#       from_secret: DOCKER_USERNAME
#     password:
#       from_secret: DOCKER_TOKEN
#     tags: latest
#     dockerfile: Dockerfile

- name: update_service
  image: docker/compose:1.29.2
  volumes:
    - name: docker-socket
      path: /var/run/docker.sock
  commands:
    - docker -v
    - nohup dockerd &
    - docker ps
    - docker-compose pull
    - docker-compose up -d
