kind: pipeline
type: docker
name: sick-pipeline

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: DOCKERHUB_USERNAME/pcjazzerne
    username:
      from_secret: DOCKERHUB_USERNAME
    password:
      from_secret: DOCKER_TOKEN
    tags: 
      - latest