kind: pipeline
name: default

trigger:
  branch:
    - main
  event:
    - pull_request

steps:
- name: install_and_build
  image: node
  commands:
    - npm install
    - npm run build

- name: deploy_to_production
  image: lholter/pcjazzerne:latest
  when:
    branch:
      - main
  commands:
    - npm start
