kind: pipeline
name: default

trigger:
  branch:
    - main

steps:
- name: build_and_push_image
  image: plugins/docker
  settings:
    repo: lholter/pcjazzerne
    registry: docker.io
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_TOKEN
    tags: latest
    dockerfile: Dockerfile

- name: update_service
  image: docker/compose:1.29.2
  commands:
    - cd $${DOCKERDIR}
    - docker-compose pull pcjazzerne-frontend
    - docker-compose up -d pcjazzerne-frontend
