kind: pipeline
name: default

trigger:
  branch:
    - main

- name: update_service
  image: docker/compose:1.29.2
  commands:
    - cd $${DOCKERDIR}
    - docker-compose pull pcjazzerne-frontend
    - docker-compose up -d pcjazzerne-frontend

- name: debug_dir
  image: alpine
  commands:
    - echo "Current Directory: $(pwd)"
    - ls -l

- name: debug_compose
  image: alpine
  commands:
    - cat $${DOCKERDIR}/docker-compose.yml

