name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pcjazzerne:latest
          
  notify-webhook:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ needs.build.result == 'success' }}
    steps:
      - name: Notify Webhook
        run: |
          payload='{"ref": "refs/heads/main", "sha": "${{ github.sha }}", "repo": "${{ github.repository }}" }'
          signature=$(echo -n "$payload" | openssl sha1 -hmac "${{ secrets.WEBHOOK_SECRET }}" | awk '{print "sha1="$1}')
          curl -X POST -H "Content-Type: application/json" \
            -H "X-Hub-Signature: $signature" \
            -d "$payload" \
            https://hook.holter.io/hooks/deploy-pcjazzerne-frontend
